# Generated by Django 3.0.7 on 2020-06-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200618_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_city',
            field=models.CharField(choices=[('LDN', 'London'), ('SYD', 'Sydney'), ('SFO', 'San Francisco'), ('SEA', 'Seattle')], default='LDN', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
