# Generated by Django 3.0.7 on 2020-06-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200619_2346'),
        ('main_app', '0008_auto_20200619_2341'),
    ]

    operations = [
    ]
